// <auto-generated />
using System;
using InsuranceComparisonService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceComparisonService.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("InsuranceComparisonService.Models.ApplicationUser", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<int>("AccessFailedCount").HasColumnType("INTEGER");
                b.Property<int?>("Age").HasColumnType("INTEGER");
                b.Property<string>("ConcurrencyStamp").HasColumnType("TEXT");
                b.Property<int?>("DrivingExperienceYears").HasColumnType("INTEGER");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<bool>("EmailConfirmed").HasColumnType("INTEGER");
                b.Property<string>("FirstName").IsRequired().HasColumnType("TEXT");
                b.Property<string>("LastName").IsRequired().HasColumnType("TEXT");
                b.Property<bool>("LockoutEnabled").HasColumnType("INTEGER");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("TEXT");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<string>("PasswordHash").HasColumnType("TEXT");
                b.Property<string>("PhoneNumber").HasColumnType("TEXT");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("INTEGER");
                b.Property<string>("SecurityStamp").HasColumnType("TEXT");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("INTEGER");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("InsuranceComparisonService.Models.InsuranceCompany", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                b.Property<string>("LogoUrl").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Website").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("InsuranceCompanies");
            });

            modelBuilder.Entity("InsuranceComparisonService.Models.InsuranceOffer", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("CompanyId").HasColumnType("INTEGER");
                b.Property<string>("Conditions").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Coverage").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasColumnType("INTEGER");
                b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<int>("Type").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("CompanyId").HasDatabaseName("IX_InsuranceOffers_CompanyId");
                b.ToTable("InsuranceOffers");
            });

            modelBuilder.Entity("InsuranceComparisonService.Models.InsurancePolicy", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<DateTime>("EndDate").HasColumnType("TEXT");
                b.Property<decimal>("FinalPrice").HasColumnType("decimal(18,2)");
                b.Property<int>("OfferId").HasColumnType("INTEGER");
                b.Property<int>("PaymentType").HasColumnType("INTEGER");
                b.Property<string>("PolicyNumber").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("StartDate").HasColumnType("TEXT");
                b.Property<int>("Status").HasColumnType("INTEGER");
                b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
                b.Property<int?>("VehicleId").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("OfferId").HasDatabaseName("IX_InsurancePolicies_OfferId");
                b.HasIndex("UserId").HasDatabaseName("IX_InsurancePolicies_UserId");
                b.HasIndex("VehicleId").HasDatabaseName("IX_InsurancePolicies_VehicleId");
                b.ToTable("InsurancePolicies");
            });

            modelBuilder.Entity("InsuranceComparisonService.Models.Review", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Comment").IsRequired().HasMaxLength(1000).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<int>("OfferId").HasColumnType("INTEGER");
                b.Property<int>("Rating").HasColumnType("INTEGER");
                b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("OfferId").HasDatabaseName("IX_Reviews_OfferId");
                b.HasIndex("UserId").HasDatabaseName("IX_Reviews_UserId");
                b.ToTable("Reviews");
            });

            modelBuilder.Entity("InsuranceComparisonService.Models.UserFavorite", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("OfferId").HasColumnType("INTEGER");
                b.Property<DateTime>("SavedAt").HasColumnType("TEXT");
                b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("OfferId").HasDatabaseName("IX_UserFavorites_OfferId");
                b.HasIndex("UserId").HasDatabaseName("IX_UserFavorites_UserId");
                b.ToTable("UserFavorites");
            });

            modelBuilder.Entity("InsuranceComparisonService.Models.Vehicle", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("AddedAt").HasColumnType("TEXT");
                b.Property<int>("Category").HasColumnType("INTEGER");
                b.Property<int>("FuelType").HasColumnType("INTEGER");
                b.Property<int>("HorsePower").HasColumnType("INTEGER");
                b.Property<string>("Make").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Model").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("PlateNumber").IsRequired().HasMaxLength(10).HasColumnType("TEXT");
                b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
                b.Property<int>("Year").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("UserId").HasDatabaseName("IX_Vehicles_UserId");
                b.ToTable("Vehicles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<string>("ConcurrencyStamp").HasColumnType("TEXT");
                b.Property<string>("Name").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex");
                b.ToTable("AspNetRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("ClaimType").HasColumnType("TEXT");
                b.Property<string>("ClaimValue").HasColumnType("TEXT");
                b.Property<string>("RoleId").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("RoleId").HasDatabaseName("IX_AspNetRoleClaims_RoleId");
                b.ToTable("AspNetRoleClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("ClaimType").HasColumnType("TEXT");
                b.Property<string>("ClaimValue").HasColumnType("TEXT");
                b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("UserId").HasDatabaseName("IX_AspNetUserClaims_UserId");
                b.ToTable("AspNetUserClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider").HasColumnType("TEXT");
                b.Property<string>("ProviderKey").HasColumnType("TEXT");
                b.Property<string>("ProviderDisplayName").HasColumnType("TEXT");
                b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
                b.HasKey("LoginProvider", "ProviderKey");
                b.HasIndex("UserId").HasDatabaseName("IX_AspNetUserLogins_UserId");
                b.ToTable("AspNetUserLogins");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId").HasColumnType("TEXT");
                b.Property<string>("RoleId").HasColumnType("TEXT");
                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId").HasDatabaseName("IX_AspNetUserRoles_RoleId");
                b.ToTable("AspNetUserRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId").HasColumnType("TEXT");
                b.Property<string>("LoginProvider").HasColumnType("TEXT");
                b.Property<string>("Name").HasColumnType("TEXT");
                b.Property<string>("Value").HasColumnType("TEXT");
                b.HasKey("UserId", "LoginProvider", "Name");
                b.ToTable("AspNetUserTokens");
            });
#pragma warning restore 612, 618
        }
    }
}
